import { useState } from 'react';
import { Phone, Mail, MapPin, Send, CheckCircle2 } from 'lucide-react';
import Seo from '../components/common/Seo';
import PageHero from '../components/common/PageHero';
import { business } from '../data/business';
import { images } from '../data/loanPrograms';

export default function Contact() {
  const [sent, setSent] = useState(false);
  const submit = (event) => { event.preventDefault(); setSent(true); };
  return <><Seo title="Contact" description="Contact Business Financial One in Coral Springs, Florida to discuss real estate or business financing." /><PageHero eyebrow="Connect With BFO" title="Let’s Talk About Your Financing Needs" text="Reach out with a question or tell us about the opportunity you are working on." image={images.commercial} cta={false} />
    <section className="section"><div className="container contact-grid"><div className="contact-info"><span className="eyebrow">Contact Information</span><h2>Business Financial One</h2><p>Speak with a financing specialist about your property, transaction or business capital needs.</p><a href={business.phoneHref}><Phone /> <span><small>Call us</small>{business.phone}</span></a><a href={business.emailHref}><Mail /> <span><small>Email us</small>{business.email}</span></a><div className="contact-address"><MapPin /><span><small>Visit us</small>{business.address[0]}<br />{business.address[1]}</span></div><div className="contact-social"><a href={business.social.x} target="_blank" rel="noreferrer" aria-label="X / Twitter">X</a><a href={business.social.instagram} target="_blank" rel="noreferrer" aria-label="Instagram">◎</a><a href={business.social.linkedin} target="_blank" rel="noreferrer" aria-label="LinkedIn">in</a></div></div>
      <div className="contact-form-wrap">{sent ? <div className="form-success"><CheckCircle2 /><h2>Message Ready</h2><p>Thank you for contacting BFO. This demonstration does not transmit information to a server. To send your message now, email <a href={business.emailHref}>{business.email}</a>.</p><button className="button button--primary" onClick={() => setSent(false)}>Send Another Message</button></div> : <form className="contact-form" onSubmit={submit}><h2>Send a Message</h2><div className="form-grid"><label>Full Name<input name="name" required autoComplete="name" /></label><label>Email Address<input type="email" name="email" required autoComplete="email" /></label><label>Phone Number<input type="tel" name="phone" required autoComplete="tel" /></label><label>Company<input name="company" autoComplete="organization" /></label><label className="field-full">Subject<select name="subject" required defaultValue=""><option value="" disabled>Select a subject</option><option>Real Estate Financing</option><option>Business Funding</option><option>Broker / Correspondent Inquiry</option><option>General Question</option></select></label><label className="field-full">Message<textarea name="message" rows="5" required /></label></div><button className="button button--primary" type="submit">Send Message <Send size={17} /></button><p className="form-note">This form is currently a front-end demonstration and does not transmit information.</p></form>}</div></div></section>
    <section className="map-placeholder"><div><MapPin /><strong>Coral Springs, Florida</strong><span>7401 Wiles Road · Coral Springs, FL 33067</span><a href="https://www.google.com/maps/search/?api=1&query=7401+Wiles+Road+Coral+Springs+FL+33067" target="_blank" rel="noreferrer">Open in Google Maps</a></div></section>
  </>;
}
